### ISSUE TITLE
Links to cluster tags and policies in README.md are broken

### ISSUE THREAD

**Issue by larsakerlund** [Azure/aks-bestpractices-ignite19#1]
### What happens

When clicking any of the following items in [README.md](https://github.com/Azure/aks-bestpractices-ignite19/blob/master/README.md#content) you are directed to the Multiple Regions Mysql Demo:

* AKS Cluster and Tags Demo
* AKS and Azure Policy

### Expected behavior

The links should direct your to their respective page.

**Comment by mohmdnofal** [comment]
thanks for reporting Lars, fixed.
